languageCode = "en"
languageName = "English"
weight = 1
title = "BinaryDigit"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "Jan 2 2006"
  logo = "img/CoffeeCroissantByFreepik.png"
  secondaryLogo = "img/CoffeeCroissantByFreepik.png"
  description = "BinaryDigit's Digital Cafe"
  copyright = "BinaryDigit 2023"

 [author]
   name = "BinaryDigit"
   image = "img/AvatarByHeyMomo.png"
   headline = "Welcome to my personal web cafe"
   bio = "My cozy personal web"
   links = [
      { envelope = "mailto:hi[at]binarydigit.cafe" },
      { mastodon = "https://social.lol/@binarydigit" },
      { twitch = "https://twitch.tv/BinaryDigit" },
      { ko-fi = "https://ko-fi.com/binarydigit" },
      { twitter = "https://twitter.com/BinaryDigit" },
      { soundcloud = "https://soundcloud.com/binarymixes" },
      { youtube = "https://youtube.com/@BinaryDigit" },
      { peertube = "https://makertube.net/a/binarydigit"},      
      { github = "https://github.com/BinaryDigitCodes" },
      { prami = "https://binarydigit.lol" },
      { location-dot = "https://binarydigit.lol/now" },
      { list = "https://status.lol/binarydigit" },
#     { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
#     { apple = "https://www.apple.com" },
#     { blogger = "https://username.blogspot.com/" },
#     { codepen = "https://codepen.io/username" },
#     { dev = "https://dev.to/username" },
#     { discord = "https://discord.gg/invitecode" },
#     { dribbble = "https://dribbble.com/username" },
#     { facebook = "https://facebook.com/username" },
#     { flickr = "https://www.flickr.com/photos/username/" },
#     { gitlab = "https://gitlab.com/username" },
#     { hashnode = "https://username.hashnode.dev" },
#     { keybase = "https://keybase.io/username" },
#     { kickstarter = "https://www.kickstarter.com/profile/username" },
#     { lastfm = "https://lastfm.com/user/username" },
#     { linkedin = "https://linkedin.com/in/username" },
#     { medium = "https://medium.com/username" },
#     { patreon = "https://www.patreon.com/username" },
#     { snapchat = "https://snapchat.com/add/username" },
#     { stack-overflow = "https://stackoverflow.com/users/userid/username" },
#     { steam = "https://steamcommunity.com/profiles/userid" },
#     { telegram = "https://t.me/username" },
#     { tiktok = "https://tiktok.com/@username" },
   ]
