languageCode = "en"
languageName = "English"
weight = 1
title = "BinaryDigit"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "Jan 2 2006"
  logo = "img/CoffeeCroissantByFreepik.png"
  secondaryLogo = "img/CoffeeCroissantByFreepik.png"
  description = "BinaryDigit's Digital Cafe"
  copyright = "BinaryDigit 2023"

 [author]
   name = "BinaryDigit"
   image = "img/AvatarByHeyMomo.png"
   headline = "Welcome to my personal web cafe"
   bio = "Projects, notes and random thoughts"
   links = [
      { twitch = "https://twitch.tv/BinaryDigit" },
      { soundcloud = "https://soundcloud.com/binarymixes" },
      { youtube = "https://youtube.com/@BinaryDigit" },
      { peertube = "https://makertube.net/a/binarydigit"}, 
      { mastodon = "https://social.lol/@binarydigit" },
      { instagram = "https://www.instagram.com/binarymixes" },     
      { prami = "https://binarydigit.lol" },
      { location-dot = "https://binarydigit.lol/now" },
      { ko-fi = "https://ko-fi.com/binarydigit" },
      { envelope = "mailto:hi[at]binarydigit.cafe" },
#     { tiktok = "https://tiktok.com/@binarydigit.cafe" },
   ]
